# Generated by Django 2.0.5 on 2018-07-25 05:40

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarInfo',
            fields=[
                ('id_no', models.AutoField(primary_key=True, serialize=False)),
                ('license_no', models.CharField(max_length=50)),
                ('make', models.CharField(max_length=50)),
                ('model', models.CharField(blank=True, max_length=50)),
                ('year', models.IntegerField(blank=True, max_length=50)),
                ('color', models.CharField(blank=True, max_length=50)),
                ('engine', models.CharField(max_length=50)),
                ('millage', models.CharField(max_length=50)),
                ('trans', models.CharField(max_length=50)),
                ('price', models.FloatField()),
                ('date', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_image_1', models.ImageField(blank=True, upload_to='profile_pics')),
                ('car_image_2', models.ImageField(blank=True, upload_to='profile_pics')),
                ('car_image_3', models.ImageField(blank=True, upload_to='profile_pics')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.CarInfo')),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('email', models.EmailField(max_length=255, primary_key=True, serialize=False)),
                ('firstname', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50)),
                ('phonenumber', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='carinfo',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.UserInfo'),
        ),
    ]
