# Generated by Django 2.0.5 on 2018-07-25 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carinfo',
            name='year',
            field=models.IntegerField(blank=True),
        ),
    ]
