# Generated by Django 2.0.5 on 2018-07-25 23:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20180725_1814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carinfo',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.UserInfo'),
        ),
    ]
