# Generated by Django 2.0.5 on 2018-07-25 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_auto_20180725_1936'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='images',
            name='car',
        ),
        migrations.AddField(
            model_name='carinfo',
            name='car_image_1',
            field=models.ImageField(blank=True, upload_to='profile_pics'),
        ),
        migrations.AddField(
            model_name='carinfo',
            name='car_image_2',
            field=models.ImageField(blank=True, upload_to='profile_pics'),
        ),
        migrations.AddField(
            model_name='carinfo',
            name='car_image_3',
            field=models.ImageField(blank=True, upload_to='profile_pics'),
        ),
        migrations.DeleteModel(
            name='Images',
        ),
    ]
