# Generated by Django 2.0.5 on 2018-07-26 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_auto_20180725_1946'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carinfo',
            name='car_image_1',
        ),
        migrations.RemoveField(
            model_name='carinfo',
            name='car_image_2',
        ),
        migrations.RemoveField(
            model_name='carinfo',
            name='car_image_3',
        ),
        migrations.AddField(
            model_name='carinfo',
            name='car_images',
            field=models.ImageField(blank=True, upload_to='car_images'),
        ),
    ]
