# Generated by Django 2.0.5 on 2018-07-26 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_auto_20180725_2003'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carinfo',
            old_name='car_images',
            new_name='car_image_1',
        ),
        migrations.AddField(
            model_name='carinfo',
            name='car_image_2',
            field=models.ImageField(blank=True, upload_to='car_images'),
        ),
        migrations.AddField(
            model_name='carinfo',
            name='car_image_3',
            field=models.ImageField(blank=True, upload_to='car_images'),
        ),
    ]
