# Generated by Django 2.0.5 on 2018-07-26 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_auto_20180725_2108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carinfo',
            name='car_image_1',
            field=models.ImageField(blank=True, default='none.jpg', upload_to='car_images'),
        ),
        migrations.AlterField(
            model_name='carinfo',
            name='car_image_2',
            field=models.ImageField(blank=True, default='none.jpg', upload_to='car_images'),
        ),
        migrations.AlterField(
            model_name='carinfo',
            name='car_image_3',
            field=models.ImageField(blank=True, default='none.jpg', upload_to='car_images'),
        ),
    ]
