# Generated by Django 2.0.5 on 2018-08-11 19:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_auto_20180725_2114'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogTopics',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('text', models.TextField()),
                ('approved', models.TextField(default='no', max_length=3)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.UserInfo')),
            ],
        ),
    ]
