# Generated by Django 2.0.5 on 2018-08-11 22:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_blogtopics'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('commenter', models.EmailField(max_length=255)),
                ('text', models.TextField()),
                ('blog_topic_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.BlogTopics')),
            ],
        ),
    ]
